/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MarketRouteImport } from './routes/market'
import { Route as NewMintsRouteImport } from './routes/new-mints'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RunnersRouteImport } from './routes/runners'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as WalletsIdRouteImport } from './routes/wallets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMintsRoute = NewMintsRouteImport.update({
  id: '/new-mints',
  path: '/new-mints',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnersRoute = RunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const WalletsIdRoute = WalletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WalletsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/eligibility': typeof EligibilityRoute
  '/execution': typeof ExecutionRoute
  '/health': typeof HealthRoute
  '/market': typeof MarketRoute
  '/new-mints': typeof NewMintsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/runners': typeof RunnersRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/wallets/$id': typeof WalletsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/eligibility': typeof EligibilityRoute
  '/execution': typeof ExecutionRoute
  '/health': typeof HealthRoute
  '/market': typeof MarketRoute
  '/new-mints': typeof NewMintsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/runners': typeof RunnersRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/wallets/$id': typeof WalletsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/eligibility': typeof EligibilityRoute
  '/execution': typeof ExecutionRoute
  '/health': typeof HealthRoute
  '/market': typeof MarketRoute
  '/new-mints': typeof NewMintsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/runners': typeof RunnersRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
  '/wallets': typeof WalletsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/wallets/$id': typeof WalletsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/eligibility'
    | '/execution'
    | '/health'
    | '/market'
    | '/new-mints'
    | '/opportunities'
    | '/projects'
    | '/runners'
    | '/settings'
    | '/trending'
    | '/upcoming'
    | '/wallets'
    | '/projects/$id'
    | '/wallets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/eligibility'
    | '/execution'
    | '/health'
    | '/market'
    | '/new-mints'
    | '/opportunities'
    | '/projects'
    | '/runners'
    | '/settings'
    | '/trending'
    | '/upcoming'
    | '/wallets'
    | '/projects/$id'
    | '/wallets/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/alerts'
    | '/eligibility'
    | '/execution'
    | '/health'
    | '/market'
    | '/new-mints'
    | '/opportunities'
    | '/projects'
    | '/runners'
    | '/settings'
    | '/trending'
    | '/upcoming'
    | '/wallets'
    | '/projects/$id'
    | '/wallets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  EligibilityRoute: typeof EligibilityRoute
  ExecutionRoute: typeof ExecutionRoute
  HealthRoute: typeof HealthRoute
  MarketRoute: typeof MarketRoute
  NewMintsRoute: typeof NewMintsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RunnersRoute: typeof RunnersRoute
  SettingsRoute: typeof SettingsRoute
  TrendingRoute: typeof TrendingRoute
  UpcomingRoute: typeof UpcomingRoute
  WalletsRoute: typeof WalletsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-mints': {
      id: '/new-mints'
      path: '/new-mints'
      fullPath: '/new-mints'
      preLoaderRoute: typeof NewMintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runners': {
      id: '/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof RunnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/wallets/$id': {
      id: '/wallets/$id'
      path: '/$id'
      fullPath: '/wallets/$id'
      preLoaderRoute: typeof WalletsIdRouteImport
      parentRoute: typeof WalletsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface WalletsRouteChildren {
  WalletsIdRoute: typeof WalletsIdRoute
}

const WalletsRouteChildren: WalletsRouteChildren = {
  WalletsIdRoute: WalletsIdRoute,
}

const WalletsRouteWithChildren =
  WalletsRoute._addFileChildren(WalletsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  EligibilityRoute: EligibilityRoute,
  ExecutionRoute: ExecutionRoute,
  HealthRoute: HealthRoute,
  MarketRoute: MarketRoute,
  NewMintsRoute: NewMintsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RunnersRoute: RunnersRoute,
  SettingsRoute: SettingsRoute,
  TrendingRoute: TrendingRoute,
  UpcomingRoute: UpcomingRoute,
  WalletsRoute: WalletsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
